name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Debug environment variables (without exposing secrets)
        run: |
          echo "🔍 Build Environment Debug:"
          echo "VITE_APP_ENV: $VITE_APP_ENV"
          echo "VITE_SUPABASE_URL is set: ${{ secrets.VITE_SUPABASE_URL != '' }}"
          echo "VITE_SUPABASE_PUBLISHABLE_KEY is set: ${{ secrets.VITE_SUPABASE_PUBLISHABLE_KEY != '' }}"
          echo "Node version: $(node --version)"
          echo "NPM version: $(npm --version)"
          # Verify environment variables are accessible
          echo "VITE_SUPABASE_URL length: ${#VITE_SUPABASE_URL}"
          echo "VITE_SUPABASE_PUBLISHABLE_KEY length: ${#VITE_SUPABASE_PUBLISHABLE_KEY}"
        env:
          VITE_APP_ENV: production
          VITE_SUPABASE_URL: ${{ secrets.VITE_SUPABASE_URL }}
          VITE_SUPABASE_PUBLISHABLE_KEY: ${{ secrets.VITE_SUPABASE_PUBLISHABLE_KEY }}

      - name: Verify secrets before build
        run: |
          echo "Pre-build secret verification:"
          if [ -z "$VITE_SUPABASE_URL" ]; then
            echo "❌ VITE_SUPABASE_URL is empty or undefined"
            exit 1
          else
            echo "✅ VITE_SUPABASE_URL is set (length: ${#VITE_SUPABASE_URL})"
          fi

          if [ -z "$VITE_SUPABASE_PUBLISHABLE_KEY" ]; then
            echo "❌ VITE_SUPABASE_PUBLISHABLE_KEY is empty or undefined"
            exit 1
          else
            echo "✅ VITE_SUPABASE_PUBLISHABLE_KEY is set (length: ${#VITE_SUPABASE_PUBLISHABLE_KEY})"
          fi
        env:
          VITE_SUPABASE_URL: ${{ secrets.VITE_SUPABASE_URL }}
          VITE_SUPABASE_PUBLISHABLE_KEY: ${{ secrets.VITE_SUPABASE_PUBLISHABLE_KEY }}

      - name: Build with Vite
        run: npm run build
        env:
          VITE_SUPABASE_URL: ${{ secrets.VITE_SUPABASE_URL }}
          VITE_SUPABASE_PUBLISHABLE_KEY: ${{ secrets.VITE_SUPABASE_PUBLISHABLE_KEY }}
          VITE_APP_ENV: production

      - name: Debug build output
        run: |
          echo "Build completed. Checking dist directory..."
          ls -la dist/
          echo "Checking for main files..."
          ls -la dist/*.html dist/*.js dist/*.css 2>/dev/null || echo "Some expected files not found"
          echo "Verifying environment variables in built files..."
          # Check if environment variables were embedded in the build
          if grep -q "VITE_SUPABASE_URL" dist/*.js 2>/dev/null; then
            echo "✅ VITE_SUPABASE_URL found in build"
          else
            echo "❌ VITE_SUPABASE_URL not found in build"
          fi
          if grep -q "VITE_SUPABASE_PUBLISHABLE_KEY" dist/*.js 2>/dev/null; then
            echo "✅ VITE_SUPABASE_PUBLISHABLE_KEY found in build"
          else
            echo "❌ VITE_SUPABASE_PUBLISHABLE_KEY not found in build"
          fi

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './dist'

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4