name: Test Secrets Access

on:
  workflow_dispatch:

jobs:
  test-secrets:
    runs-on: ubuntu-latest
    environment: github-pages

    steps:
      - name: Test secret accessibility
        run: |
          echo "Testing secret accessibility..."
          echo "VITE_SUPABASE_URL is set: ${{ secrets.VITE_SUPABASE_URL != '' }}"
          echo "VITE_SUPABASE_PUBLISHABLE_KEY is set: ${{ secrets.VITE_SUPABASE_PUBLISHABLE_KEY != '' }}"

          # Test if secrets are actually accessible as environment variables
          if [ -n "$VITE_SUPABASE_URL" ]; then
            echo "✅ VITE_SUPABASE_URL is accessible (length: ${#VITE_SUPABASE_URL})"
          else
            echo "❌ VITE_SUPABASE_URL is empty or not accessible"
          fi

          if [ -n "$VITE_SUPABASE_PUBLISHABLE_KEY" ]; then
            echo "✅ VITE_SUPABASE_PUBLISHABLE_KEY is accessible (length: ${#VITE_SUPABASE_PUBLISHABLE_KEY})"
          else
            echo "❌ VITE_SUPABASE_PUBLISHABLE_KEY is empty or not accessible"
          fi

          # Test first few characters (obfuscated for security)
          if [ -n "$VITE_SUPABASE_URL" ]; then
            echo "URL starts with: ${VITE_SUPABASE_URL:0:8}..."
          fi

          if [ -n "$VITE_SUPABASE_PUBLISHABLE_KEY" ]; then
            echo "Key starts with: ${VITE_SUPABASE_PUBLISHABLE_KEY:0:8}..."
          fi
        env:
          VITE_SUPABASE_URL: ${{ secrets.VITE_SUPABASE_URL }}
          VITE_SUPABASE_PUBLISHABLE_KEY: ${{ secrets.VITE_SUPABASE_PUBLISHABLE_KEY }}